# Generated by Django 3.1.13 on 2021-11-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211121_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_id',
            field=models.IntegerField(auto_created=True, blank=True, null=True),
        ),
    ]
